# Modifying Data - Updating rows and columns

In [62]:
import pandas as pd
people = {
    "first" : ["Devraj","Yash", "Tarun"],
    "last" : ["Charan", "Burad", "Yadav"],
    "email" : ["devrajcharan@gmail.com", "yashburad@gmail.com", "tarunyadav@gmail.com"]
}
df = pd.DataFrame(people)
df

    first    last                   email
0  Devraj  Charan  devrajcharan@gmail.com
1    Yash   Burad     yashburad@gmail.com
2   Tarun   Yadav    tarunyadav@gmail.com

In [63]:
df.columns

Index(['first', 'last', 'email'], dtype='object')

In [64]:
#to rename column]
df.columns = ['first name', 'last name', 'email']
df

  first name last name                   email
0     Devraj    Charan  devrajcharan@gmail.com
1       Yash     Burad     yashburad@gmail.com
2      Tarun     Yadav    tarunyadav@gmail.com

In [65]:
#to upper case all columns
df.columns = [x.lower() for x in df.columns]
df

  first name last name                   email
0     Devraj    Charan  devrajcharan@gmail.com
1       Yash     Burad     yashburad@gmail.com
2      Tarun     Yadav    tarunyadav@gmail.com

In [66]:
#to remove spaces or anything we use string methods
df.columns = df.columns.str.replace(' ', '_')
df

  first_name last_name                   email
0     Devraj    Charan  devrajcharan@gmail.com
1       Yash     Burad     yashburad@gmail.com
2      Tarun     Yadav    tarunyadav@gmail.com

In [67]:
#to change particular columns, use dictionary
df.rename(columns= {'first_name': 'first',
                    'last_name' : 'last'})
#but it just create a copy, do not change names of original DataFrame

    first    last                   email
0  Devraj  Charan  devrajcharan@gmail.com
1    Yash   Burad     yashburad@gmail.com
2   Tarun   Yadav    tarunyadav@gmail.com

In [68]:
df

  first_name last_name                   email
0     Devraj    Charan  devrajcharan@gmail.com
1       Yash     Burad     yashburad@gmail.com
2      Tarun     Yadav    tarunyadav@gmail.com

In [69]:
#to change for original use, inplace = True
df.rename(columns= {'first_name': 'first', 'last_name' : 'last'},inplace = True)
df

    first    last                   email
0  Devraj  Charan  devrajcharan@gmail.com
1    Yash   Burad     yashburad@gmail.com
2   Tarun   Yadav    tarunyadav@gmail.com

## For rows

In [70]:
#for particular row
df.loc[2] = ['Tarun','Yadav','yadavtarun@gmail.com']
df

    first    last                   email
0  Devraj  Charan  devrajcharan@gmail.com
1    Yash   Burad     yashburad@gmail.com
2   Tarun   Yadav    yadavtarun@gmail.com

In [71]:
#for specific element
df.loc[2,'email'] = 'tarunyadav@gmail.com'
df
#you can do this for multiple columns to by passing a list
# df.loc[0,['col_1',''col_2' ]] = ['new_col1',''new_col2']

    first    last                   email
0  Devraj  Charan  devrajcharan@gmail.com
1    Yash   Burad     yashburad@gmail.com
2   Tarun   Yadav    tarunyadav@gmail.com

In [72]:
#but its prefered to use df.at when modifying specifir=c value do avoid overhead from loc/iloc
df.at[0,'email'] = 'charandevraj@gmail.com'
df

    first    last                   email
0  Devraj  Charan  charandevraj@gmail.com
1    Yash   Burad     yashburad@gmail.com
2   Tarun   Yadav    tarunyadav@gmail.com

In [73]:
#you can use filter to modify more efficiently
filt = (df['email'] == 'charandevraj@gmail.com')
df.loc[filt,'email'] = 'devrajcharan@gmail.com'
df

    first    last                   email
0  Devraj  Charan  devrajcharan@gmail.com
1    Yash   Burad     yashburad@gmail.com
2   Tarun   Yadav    tarunyadav@gmail.com

In [74]:
#to apply sting methods on paticular value
df['email'] = df['email'].str.upper()
df

    first    last                   email
0  Devraj  Charan  DEVRAJCHARAN@GMAIL.COM
1    Yash   Burad     YASHBURAD@GMAIL.COM
2   Tarun   Yadav    TARUNYADAV@GMAIL.COM

In [75]:
df.loc[[0,2],'email'] = df.loc[[0,2],'email'].str.lower()
df

    first    last                   email
0  Devraj  Charan  devrajcharan@gmail.com
1    Yash   Burad     YASHBURAD@GMAIL.COM
2   Tarun   Yadav    tarunyadav@gmail.com

## Methods to modify multiple rows
## 1. apply
## 2. map
## 3. applymap
## 4. replace

In [76]:
#apply - To apply any function on whole series
df['email'].apply(len)

0    22
1    19
2    20
Name: email, dtype: int64

In [77]:
#you can also use user created function ->
def update_email(email):
    return email.lower()
df['email'].apply(update_email)

0    devrajcharan@gmail.com
1       yashburad@gmail.com
2      tarunyadav@gmail.com
Name: email, dtype: object

In [78]:
df['email'] = df['email'].apply(update_email)
df

    first    last                   email
0  Devraj  Charan  devrajcharan@gmail.com
1    Yash   Burad     yashburad@gmail.com
2   Tarun   Yadav    tarunyadav@gmail.com

In [79]:
#you can also apply lemda function ->
df['email'] = df['email'].apply(lambda email: email.upper())
df

    first    last                   email
0  Devraj  Charan  DEVRAJCHARAN@GMAIL.COM
1    Yash   Burad     YASHBURAD@GMAIL.COM
2   Tarun   Yadav    TARUNYADAV@GMAIL.COM

In [80]:
#applying on whole DataFrame
df.apply(len) #applies funtion on each series

first    3
last     3
email    3
dtype: int64

In [81]:
df.apply(len, axis = 'columns')

0    3
1    3
2    3
dtype: int64

In [82]:
df.apply(min)

first                    Devraj
last                      Burad
email    DEVRAJCHARAN@GMAIL.COM
dtype: object

In [83]:
df.apply(min, axis = 1)

0                  Charan
1                   Burad
2    TARUNYADAV@GMAIL.COM
dtype: object

In [ ]:
# applymap - to apply any function on each element of a DataFrame
df.applymap(len) #it is removed now, no longer works in newer version of pandas
#instead just use df.map()

C:\Users\devra\AppData\Local\Temp\ipykernel_14300\946274576.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(len)

   first  last  email
0      6     6     22
1      4     5     19
2      5     5     20

In [85]:
df

    first    last                   email
0  Devraj  Charan  DEVRAJCHARAN@GMAIL.COM
1    Yash   Burad     YASHBURAD@GMAIL.COM
2   Tarun   Yadav    TARUNYADAV@GMAIL.COM

In [86]:
df['email'] = df['email'].apply(str.lower)
df

    first    last                   email
0  Devraj  Charan  devrajcharan@gmail.com
1    Yash   Burad     yashburad@gmail.com
2   Tarun   Yadav    tarunyadav@gmail.com

In [87]:
# map - only works on series, used for substituing each value in a series
df['first'].map({'Devraj': 'Dev', 'Yash': 'Yeshu'})
# We get NaN for not provided value, to avoid that use 'replace' method

0      Dev
1    Yeshu
2      NaN
Name: first, dtype: object

In [ ]:
#replace - to replace particular values of a series
df['first'].replace({'Devraj': 'Dev', 'Yash': 'Yeshu'})
df #this won't update the original df

    first    last                   email
0  Devraj  Charan  devrajcharan@gmail.com
1    Yash   Burad     yashburad@gmail.com
2   Tarun   Yadav    tarunyadav@gmail.com

In [89]:
#replace - to replace particular values of a series
modify = df['first'].replace({'Devraj': 'Dev', 'Yash': 'Yeshu'})
modify

0      Dev
1    Yeshu
2    Tarun
Name: first, dtype: object

In [90]:
df['first'] = modify
df

   first    last                   email
0    Dev  Charan  devrajcharan@gmail.com
1  Yeshu   Burad     yashburad@gmail.com
2  Tarun   Yadav    tarunyadav@gmail.com