In [49]:
import pandas as pd

df = pd.read_csv('data_2024/survey_results_public.csv')
schema_df = pd.read_csv('data_2024/survey_results_schema.csv')
df

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,NaN,NaN,NaN,NaN,Yes,Very favorable,Increase productivity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,MacOS;Windows,MacOS,NaN,NaN,NaN,Microsoft Teams;Slack,Slack,Slack,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.0,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,37,27,Developer Experience,NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,C#,C#,C#,Firebase Realtime Database,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,Google Cloud,ASP.NET CORE,ASP.NET CORE,ASP.NET CORE,Rasberry Pi,Rasberry Pi,Rasberry Pi,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,MSBuild,MSBuild,MSBuild,Visual Studio,Visual Studio,Visual Studio,Windows,Windows,NaN,NaN,NaN,Google Chat;Google Meet;Microsoft Teams;Zoom,Google Chat;Google Meet;Zoom,Google Chat;Google Meet;Zoom,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow B...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,4,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Canada,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,Amazon Web Services (AWS),jQuery;Next.js;Node.js;React;WordPress,jQuery;Next.js;Node.js;React,jQuery;Next.js;Node.js;React,Rasberry Pi,NaN,NaN,NumPy;Pandas;Ruff;TensorFlow,NaN,NaN,Docker;npm;Pip,Docker;Kubernetes;npm,Docker;npm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,No,NaN,Quickly finding code solutions,"No, not really",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,Bad at handling complex tasks,Learning about a codebase;Project planning;Wri...,Testing code;Committing and reviewing code;Pre...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,9,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Norway,NaN,NaN,C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,NaN,NaN,NaN,CMake;Cargo;Rasberry Pi,CMake;Rasberry Pi,CMake;Rasberry Pi,NaN,NaN,NaN,APT;Make;npm,APT;Make,APT;Make,Vim,Vim,Vim,Other (please specify):,NaN,GitHub Discussions;Markdown File;Obsidian;Stac...,GitHub Discussions;Markdown File;Obsidian,GitHub Discussions;Markdown File;Obsidian,Discord;Whatsapp,Discord;Whatsapp,Discord;Whatsapp,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Engage with com...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65432,65433,I am a developer by profession,18-24 years old,"Employed, full-time",Remote,Apples,Hobby;School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","On the job training;School (i.e., University, ...",NaN,NaN,5,3,Blockchain,2 to 9 employees,I have some influence,Ask developers I know/work with;Ask a generati...,Is ready-to-go but also customizable for growt...,APIs;Integrated developer community;Quality su...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Favorable,Increase productivity;Greater efficiency;Speed...,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Project planning;Wri...,Debugging and getting help;Testing code;Deploy...,Committing and reviewing code,Writing code;Search for answers;Generating con...,NaN,Learning about a codebase;Project planning;Doc...,NaN,NaN,No,Circulating misinformation or disinformation,"AI tools lack context of codebase, internal a...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65433,65434,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65434,65435,I am a developer by profession,25-34 years old,"Employed, full-time",In-person,Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Social ...,API document(s) and/or SDK document(s);AI-powe...,9,5,"Developer, mobile","1,000 to 4,999 employees",I have little or no influence,Ask developers I know/work with;Ask a generati...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65435,65436,I am a developer by profession,18-24 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Profe...,"Secondary school (e.g. American high school, G...",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,5,2,"Developer, back-end",20 to 99 employees,I have some influence,Start a free trial;Ask developers I know/work ...,Is ready-to-go but also customizable for growt...,APIs;Customization;Connected to an open source...,Germany,EUR European Euro,NaN,C;C++;Go;Lua;Objective-C;Python;Rust;SQL,Rust;SQL,Rust;SQL,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,Angular;Node.js;React,NaN,NaN,Arduino;CMake;Cargo;GNU GCC;Rasberry Pi,Cargo;GNU GCC;Rasberry Pi,Cargo;GNU GCC;Rasberry Pi,GTK;OpenGL,NaN,NaN,Ansible;APT;Docker;Make;npm;Pip;Podman,Ansible;APT;Docker;Make;npm;Pip;Podman,Ansible;APT;Docker;Make;npm;Pip;Podman,Vim;Visual Studio Code,Vim;Visual Studio Code,Vim;Visual Studio Code,Android;Other Linux-based;Ubuntu;Windows,Fedora;Other Linux-based;Ubuntu,Confluence;Jira;Markdown File;Obsidian;Trello,Confluence;Jira;Markdown File;Trello,Confluence;Jira;Markdown File;Trello,Discord;Jitsi;Microsoft Teams;Whatsapp,Discord;Jitsi;Whatsapp,Discord;Jitsi;Whatsapp,NaN,NaN,NaN,Stack Overflow;Stack Exchange,A few times per month or weekly,No,NaN,Quickly finding code solutions,"No, not really","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
65436,65437,I code primarily as a hobby,18-24 years old,"Student, full-time",NaN,Apples,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C;HTML/CSS;Java;JavaScript;PHP;Python;TypeScript,JavaScript;Python;TypeScript,JavaScript;Python;TypeScript,MongoDB;MySQL;Oracle;PostgreSQL,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Cloudflare;Google Cl...,Cloudflare;Google Cloud;Netlify;Vercel,Cloudflare;Google Cloud;Netlify;Vercel,Django;Express;jQuery;Next.js;Node.js;React,Django;Express;Next.js;Node.js;React,Django;Express;Next.js;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,npm;Pip;Vite,npm;Pip;Vite,npm;Pip;Vite,Visual Studio Code,Visual Studio Code,Visual Studio Code,Windows,MacOS;Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,Yes,Less than once per month or monthly,Quickly finding code solutions,"Yes, somewhat",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
pd.set_option('display.max_columns', 200)
pd.set_option('display.max_rows', 88)
df.shape

(65437, 114)

In [51]:
df.head() #if no value is passed shows  rows, you can also pass value, df.head(10) -> will show 10 rows
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65437 entries, 0 to 65436
Columns: 114 entries, ResponseId to JobSat
dtypes: float64(13), int64(1), object(100)
memory usage: 56.9+ MB

In [52]:

schema_df.head(11)
schema_df.tail(6)

,qid,qname,question,force_resp,type,selector
81,QID337,JobSatPoints_6,Improving quality of code and developer enviro...,NaN,MC,MAVR
82,QID337,JobSatPoints_7,"Learning and using new technology, including p...",NaN,MC,MAVR
83,QID337,JobSatPoints_8,"Designing and building environments, databases...",NaN,MC,MAVR
84,QID337,JobSatPoints_9,"Being a power user of a tool, developer langua...",NaN,MC,MAVR
85,QID337,JobSatPoints_10,Working with new and/or top-quality hardware,NaN,MC,MAVR
86,QID337,JobSatPoints_11,A well-staffed/sourced internal network that m...,NaN,MC,MAVR

In [53]:
pd.set_option('display.max_rows', 20)
schema_df

,qid,qname,question,force_resp,type,selector
0,QID2,MainBranch,Which of the following options best describes ...,True,MC,SAVR
1,QID127,Age,What is your age?*,True,MC,SAVR
2,QID296,Employment,Which of the following best describes your cur...,True,MC,MAVR
3,QID308,RemoteWork,Which best describes your current work situation?,False,MC,SAVR
4,QID341,Check,Just checking to make sure you are paying atte...,True,MC,SAVR
...,...,...,...,...,...,...
82,QID337,JobSatPoints_7,"Learning and using new technology, including p...",NaN,MC,MAVR
83,QID337,JobSatPoints_8,"Designing and building environments, databases...",NaN,MC,MAVR
84,QID337,JobSatPoints_9,"Being a power user of a tool, developer langua...",NaN,MC,MAVR
85,QID337,JobSatPoints_10,Working with new and/or top-quality hardware,NaN,MC,MAVR
86,QID337,JobSatPoints_11,A well-staffed/sourced internal network that m...,NaN,MC,MAVR

## Experimenting methods from 'Pandas_2.ipynb'

In [54]:
df.shape

(65437, 114)

In [55]:
#to see all columns
pd.set_option('display.max_seq_items', None)
df.columns

Index(['ResponseId', 'MainBranch', 'Age', 'Employment', 'RemoteWork', 'Check',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       'TechDoc', 'YearsCode', 'YearsCodePro', 'DevType', 'OrgSize',
       'PurchaseInfluence', 'BuyNewTool', 'BuildvsBuy', 'TechEndorse',
       'Country', 'Currency', 'CompTotal', 'LanguageHaveWorkedWith',
       'LanguageWantToWorkWith', 'LanguageAdmired', 'DatabaseHaveWorkedWith',
       'DatabaseWantToWorkWith', 'DatabaseAdmired', 'PlatformHaveWorkedWith',
       'PlatformWantToWorkWith', 'PlatformAdmired', 'WebframeHaveWorkedWith',
       'WebframeWantToWorkWith', 'WebframeAdmired', 'EmbeddedHaveWorkedWith',
       'EmbeddedWantToWorkWith', 'EmbeddedAdmired', 'MiscTechHaveWorkedWith',
       'MiscTechWantToWorkWith', 'MiscTechAdmired', 'ToolsTechHaveWorkedWith',
       'ToolsTechWantToWorkWith', 'ToolsTechAdmired',
       'NEWCollabToolsHaveWorkedWith', 'NEWCollabToolsWantToWorkWith',
       'NEWCollabToolsAdmired', 'OpSysPersonal use', 'OpSysProfessional use',
       'OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith',
       'OfficeStackAsyncAdmired', 'OfficeStackSyncHaveWorkedWith',
       'OfficeStackSyncWantToWorkWith', 'OfficeStackSyncAdmired',
       'AISearchDevHaveWorkedWith', 'AISearchDevWantToWorkWith',
       'AISearchDevAdmired', 'NEWSOSites', 'SOVisitFreq', 'SOAccount',
       'SOPartFreq', 'SOHow', 'SOComm', 'AISelect', 'AISent', 'AIBen', 'AIAcc',
       'AIComplex', 'AIToolCurrently Using', 'AIToolInterested in Using',
       'AIToolNot interested in Using', 'AINextMuch more integrated',
       'AINextNo change', 'AINextMore integrated', 'AINextLess integrated',
       'AINextMuch less integrated', 'AIThreat', 'AIEthics', 'AIChallenges',
       'TBranch', 'ICorPM', 'WorkExp', 'Knowledge_1', 'Knowledge_2',
       'Knowledge_3', 'Knowledge_4', 'Knowledge_5', 'Knowledge_6',
       'Knowledge_7', 'Knowledge_8', 'Knowledge_9', 'Frequency_1',
       'Frequency_2', 'Frequency_3', 'TimeSearching', 'TimeAnswering',
       'Frustration', 'ProfessionalTech', 'ProfessionalCloud',
       'ProfessionalQuestion', 'Industry', 'JobSatPoints_1', 'JobSatPoints_4',
       'JobSatPoints_5', 'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8',
       'JobSatPoints_9', 'JobSatPoints_10', 'JobSatPoints_11', 'SurveyLength',
       'SurveyEase', 'ConvertedCompYearly', 'JobSat'],
      dtype='object')

In [56]:
#to change setting to defualt
pd.reset_option('display.max_rows')
#to access a columns -> df.coumnname / df['columns-Name']
df["SOAccount"]

0        NaN
1        Yes
2        Yes
3         No
4        Yes
        ...
65432    NaN
65433    NaN
65434    NaN
65435     No
65436    Yes
Name: SOAccount, Length: 65437, dtype: object

In [57]:
#To count any value -> df[' '].valuecounts
df['SOAccount'].value_counts()

SOAccount
Yes                        45453
No                          9628
Not sure/can't remember     4479
Name: count, dtype: int64

In [58]:
#to get specific rows , columns
#df.loc - by label, df.iloc - by index
df.loc[[1,2,3,4,5,34,67], 'SOAccount']

1     Yes
2     Yes
3      No
4     Yes
5     Yes
34    Yes
67    Yes
Name: SOAccount, dtype: object

In [59]:
#We can also us sllicing, last value is inclusive when using df.iloc
df.loc[0:5,'SOAccount']

0    NaN
1    Yes
2    Yes
3     No
4    Yes
5    Yes
Name: SOAccount, dtype: object

In [60]:
df.loc[0:4,'SOVisitFreq':'SOComm']

,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm
0,NaN,NaN,NaN,NaN,NaN
1,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely"
2,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely"
3,Daily or almost daily,No,NaN,Quickly finding code solutions,"No, not really"
4,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Engage with com...,"Yes, definitely"

## Using operations (indexing) from Pandas_3

In [61]:
df

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,NaN,NaN,NaN,NaN,Yes,Very favorable,Increase productivity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,MacOS;Windows,MacOS,NaN,NaN,NaN,Microsoft Teams;Slack,Slack,Slack,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.0,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,37,27,Developer Experience,NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,C#,C#,C#,Firebase Realtime Database,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,Google Cloud,ASP.NET CORE,ASP.NET CORE,ASP.NET CORE,Rasberry Pi,Rasberry Pi,Rasberry Pi,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,MSBuild,MSBuild,MSBuild,Visual Studio,Visual Studio,Visual Studio,Windows,Windows,NaN,NaN,NaN,Google Chat;Google Meet;Microsoft Teams;Zoom,Google Chat;Google Meet;Zoom,Google Chat;Google Meet;Zoom,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow B...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,4,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Canada,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,Amazon Web Services (AWS),jQuery;Next.js;Node.js;React;WordPress,jQuery;Next.js;Node.js;React,jQuery;Next.js;Node.js;React,Rasberry Pi,NaN,NaN,NumPy;Pandas;Ruff;TensorFlow,NaN,NaN,Docker;npm;Pip,Docker;Kubernetes;npm,Docker;npm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,No,NaN,Quickly finding code solutions,"No, not really",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,Bad at handling complex tasks,Learning about a codebase;Project planning;Wri...,Testing code;Committing and reviewing code;Pre...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,9,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Norway,NaN,NaN,C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,NaN,NaN,NaN,CMake;Cargo;Rasberry Pi,CMake;Rasberry Pi,CMake;Rasberry Pi,NaN,NaN,NaN,APT;Make;npm,APT;Make,APT;Make,Vim,Vim,Vim,Other (please specify):,NaN,GitHub Discussions;Markdown File;Obsidian;Stac...,GitHub Discussions;Markdown File;Obsidian,GitHub Discussions;Markdown File;Obsidian,Discord;Whatsapp,Discord;Whatsapp,Discord;Whatsapp,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Engage with com...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65432,65433,I am a developer by profession,18-24 years old,"Employed, full-time",Remote,Apples,Hobby;School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","On the job training;School (i.e., University, ...",NaN,NaN,5,3,Blockchain,2 to 9 employees,I have some influence,Ask developers I know/work with;Ask a generati...,Is ready-to-go but also customizable for growt...,APIs;Integrated developer community;Quality su...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Favorable,Increase productivity;Greater efficiency;Speed...,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Project planning;Wri...,Debugging and getting help;Testing code;Deploy...,Committing and reviewing code,Writing code;Search for answers;Generating con...,NaN,Learning about a codebase;Project planning;Doc...,NaN,NaN,No,Circulating misinformation or disinformation,"AI tools lack context of codebase, internal a...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65433,65434,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65434,65435,I am a developer by profession,25-34 years old,"Employed, full-time",In-person,Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Social ...,API document(s) and/or SDK document(s);AI-powe...,9,5,"Developer, mobile","1,000 to 4,999 employees",I have little or no influence,Ask developers I know/work with;Ask a generati...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65435,65436,I am a developer by profession,18-24 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Profe...,"Secondary school (e.g. American high school, G...",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,5,2,"Developer, back-end",20 to 99 employees,I have some influence,Start a free trial;Ask developers I know/work ...,Is ready-to-go but also customizable for growt...,APIs;Customization;Connected to an open source...,Germany,EUR European Euro,NaN,C;C++;Go;Lua;Objective-C;Python;Rust;SQL,Rust;SQL,Rust;SQL,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,Angular;Node.js;React,NaN,NaN,Arduino;CMake;Cargo;GNU GCC;Rasberry Pi,Cargo;GNU GCC;Rasberry Pi,Cargo;GNU GCC;Rasberry Pi,GTK;OpenGL,NaN,NaN,Ansible;APT;Docker;Make;npm;Pip;Podman,Ansible;APT;Docker;Make;npm;Pip;Podman,Ansible;APT;Docker;Make;npm;Pip;Podman,Vim;Visual Studio Code,Vim;Visual Studio Code,Vim;Visual Studio Code,Android;Other Linux-based;Ubuntu;Windows,Fedora;Other Linux-based;Ubuntu,Confluence;Jira;Markdown File;Obsidian;Trello,Confluence;Jira;Markdown File;Trello,Confluence;Jira;Markdown File;Trello,Discord;Jitsi;Microsoft Teams;Whatsapp,Discord;Jitsi;Whatsapp,Discord;Jitsi;Whatsapp,NaN,NaN,NaN,Stack Overflow;Stack Exchange,A few times per month or weekly,No,NaN,Quickly finding code solutions,"No, not really","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
65436,65437,I code primarily as a hobby,18-24 years old,"Student, full-time",NaN,Apples,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C;HTML/CSS;Java;JavaScript;PHP;Python;TypeScript,JavaScript;Python;TypeScript,JavaScript;Python;TypeScript,MongoDB;MySQL;Oracle;PostgreSQL,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Cloudflare;Google Cl...,Cloudflare;Google Cloud;Netlify;Vercel,Cloudflare;Google Cloud;Netlify;Vercel,Django;Express;jQuery;Next.js;Node.js;React,Django;Express;Next.js;Node.js;React,Django;Express;Next.js;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,npm;Pip;Vite,npm;Pip;Vite,npm;Pip;Vite,Visual Studio Code,Visual Studio Code,Visual Studio Code,Windows,MacOS;Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,Yes,Less than once per month or monthly,Quickly finding code solutions,"Yes, somewhat",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
# we can set index also by
df1 = pd.read_csv('data_2024/survey_results_public.csv', index_col = 'ResponseId')
df1.head()

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,NaN,NaN,NaN,NaN,Yes,Very favorable,Increase productivity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,MacOS;Windows,MacOS,NaN,NaN,NaN,Microsoft Teams;Slack,Slack,Slack,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.0,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,37,27,Developer Experience,NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,C#,C#,C#,Firebase Realtime Database,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,Google Cloud,ASP.NET CORE,ASP.NET CORE,ASP.NET CORE,Rasberry Pi,Rasberry Pi,Rasberry Pi,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,MSBuild,MSBuild,MSBuild,Visual Studio,Visual Studio,Visual Studio,Windows,Windows,NaN,NaN,NaN,Google Chat;Google Meet;Microsoft Teams;Zoom,Google Chat;Google Meet;Zoom,Google Chat;Google Meet;Zoom,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow B...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,4,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Canada,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,Amazon Web Services (AWS),jQuery;Next.js;Node.js;React;WordPress,jQuery;Next.js;Node.js;React,jQuery;Next.js;Node.js;React,Rasberry Pi,NaN,NaN,NumPy;Pandas;Ruff;TensorFlow,NaN,NaN,Docker;npm;Pip,Docker;Kubernetes;npm,Docker;npm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,No,NaN,Quickly finding code solutions,"No, not really",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,Bad at handling complex tasks,Learning about a codebase;Project planning;Wri...,Testing code;Committing and reviewing code;Pre...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,9,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Norway,NaN,NaN,C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,NaN,NaN,NaN,CMake;Cargo;Rasberry Pi,CMake;Rasberry Pi,CMake;Rasberry Pi,NaN,NaN,NaN,APT;Make;npm,APT;Make,APT;Make,Vim,Vim,Vim,Other (please specify):,NaN,GitHub Discussions;Markdown File;Obsidian;Stac...,GitHub Discussions;Markdown File;Obsidian,GitHub Discussions;Markdown File;Obsidian,Discord;Whatsapp,Discord;Whatsapp,Discord;Whatsapp,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Engage with com...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

## Filtering operation from Pandas_4

In [63]:
df1.columns

Index(['MainBranch', 'Age', 'Employment', 'RemoteWork', 'Check',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       'TechDoc', 'YearsCode', 'YearsCodePro', 'DevType', 'OrgSize',
       'PurchaseInfluence', 'BuyNewTool', 'BuildvsBuy', 'TechEndorse',
       'Country', 'Currency', 'CompTotal', 'LanguageHaveWorkedWith',
       'LanguageWantToWorkWith', 'LanguageAdmired', 'DatabaseHaveWorkedWith',
       'DatabaseWantToWorkWith', 'DatabaseAdmired', 'PlatformHaveWorkedWith',
       'PlatformWantToWorkWith', 'PlatformAdmired', 'WebframeHaveWorkedWith',
       'WebframeWantToWorkWith', 'WebframeAdmired', 'EmbeddedHaveWorkedWith',
       'EmbeddedWantToWorkWith', 'EmbeddedAdmired', 'MiscTechHaveWorkedWith',
       'MiscTechWantToWorkWith', 'MiscTechAdmired', 'ToolsTechHaveWorkedWith',
       'ToolsTechWantToWorkWith', 'ToolsTechAdmired',
       'NEWCollabToolsHaveWorkedWith', 'NEWCollabToolsWantToWorkWith',
       'NEWCollabToolsAdmired', 'OpSysPersonal use', 'OpSysProfessional use',
       'OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith',
       'OfficeStackAsyncAdmired', 'OfficeStackSyncHaveWorkedWith',
       'OfficeStackSyncWantToWorkWith', 'OfficeStackSyncAdmired',
       'AISearchDevHaveWorkedWith', 'AISearchDevWantToWorkWith',
       'AISearchDevAdmired', 'NEWSOSites', 'SOVisitFreq', 'SOAccount',
       'SOPartFreq', 'SOHow', 'SOComm', 'AISelect', 'AISent', 'AIBen', 'AIAcc',
       'AIComplex', 'AIToolCurrently Using', 'AIToolInterested in Using',
       'AIToolNot interested in Using', 'AINextMuch more integrated',
       'AINextNo change', 'AINextMore integrated', 'AINextLess integrated',
       'AINextMuch less integrated', 'AIThreat', 'AIEthics', 'AIChallenges',
       'TBranch', 'ICorPM', 'WorkExp', 'Knowledge_1', 'Knowledge_2',
       'Knowledge_3', 'Knowledge_4', 'Knowledge_5', 'Knowledge_6',
       'Knowledge_7', 'Knowledge_8', 'Knowledge_9', 'Frequency_1',
       'Frequency_2', 'Frequency_3', 'TimeSearching', 'TimeAnswering',
       'Frustration', 'ProfessionalTech', 'ProfessionalCloud',
       'ProfessionalQuestion', 'Industry', 'JobSatPoints_1', 'JobSatPoints_4',
       'JobSatPoints_5', 'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8',
       'JobSatPoints_9', 'JobSatPoints_10', 'JobSatPoints_11', 'SurveyLength',
       'SurveyEase', 'ConvertedCompYearly', 'JobSat'],
      dtype='object')

In [64]:
high_experience = (df['WorkExp'] >= 50 )
df_exp = df.loc[high_experience, ['ResponseId','WorkExp' ,'EdLevel','Country','LanguageWantToWorkWith']]
df_exp

,ResponseId,WorkExp,EdLevel,Country,LanguageWantToWorkWith
819,820,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Denmark,C#;Prolog;TypeScript;VBA
1019,1020,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America,Bash/Shell (all shells);HTML/CSS;Java;JavaScri...
1779,1780,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America,Lisp;SQL
2220,2221,50.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Argentina,C;C++;JavaScript;MicroPython;PowerShell;Python
2757,2758,50.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Taiwan,C;C++;Julia;Python
2911,2912,50.0,Some college/university study without earning ...,United States of America,C#;C++;Delphi;SQL;Visual Basic (.Net)
6110,6111,50.0,Some college/university study without earning ...,United States of America,Bash/Shell (all shells);C#;HTML/CSS;JavaScript...
6661,6662,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America,C;C#;HTML/CSS;Python;Swift
8256,8257,50.0,"Secondary school (e.g. American high school, G...",Nigeria,Perl;PHP;PowerShell;Prolog;Python;R;Ruby;Rust;...
11548,11549,50.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Republic of North Macedonia,Delphi;Fortran;Perl;PHP
12501,12502,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Germany,C;C++;Python
12747,12748,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Bangladesh,JavaScript
17925,17926,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America,Bash/Shell (all shells);C;Go;Python;SQL
18954,18955,50.0,Some college/university study without earning ...,Canada,HTML/CSS;JavaScript
19137,19138,50.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",United States of America,C#;HTML/CSS;PHP;Python;R;SQL
19601,19602,50.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",United States of America,Bash/Shell (all shells);JavaScript;Python;Rust...
19712,19713,50.0,Some college/university study without earning ...,Philippines,NaN
20037,20038,50.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Niger,Ada;Apex;Assembly;Bash/Shell (all shells);C;C#...
20562,20563,50.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",United States of America,Clojure;Julia
20816,20817,50.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",United States of America,Python;R;Ruby
21252,21253,50.0,Some college/university study without earning ...,Israel,C;C#;Cobol;Java;Python;SQL
23384,23385,50.0,Primary/elementary school,Albania,Elixir;Lisp;Prolog
23683,23684,50.0,Something else,Bangladesh,Ada;Apex;Assembly;Bash/Shell (all shells);C;C#...
25108,25109,50.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",United States of America,Assembly;C;C++;Fortran
26142,26143,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America,C;C++;JavaScript;Python
27190,27191,50.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Nigeria,Ada
28184,28185,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America,Bash/Shell (all shells);C++;SQL
29399,29400,50.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",United States of America,C#;C++;Delphi;HTML/CSS;JavaScript;MATLAB;Power...
30896,30897,50.0,Some college/university study without earning ...,United States of America,Python
32672,32673,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Canada,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...
33101,33102,50.0,"Secondary school (e.g. American high school, G...",Afghanistan,Ada
33701,33702,50.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",United States of America,Apex;HTML/CSS;Java;JavaScript;SQL
34278,34279,50.0,Something else,Nomadic,Ada;Apex;Assembly;Bash/Shell (all shells);C;C#...
35090,35091,50.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Iceland,NaN
37770,37771,50.0,Some college/university study without earning ...,Germany,Java;JavaScript;Kotlin;Objective-C;Swift;TypeS...
38026,38027,50.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Thailand,NaN
38430,38431,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Netherlands,Assembly;C;C#;C++;Python
39055,39056,50.0,Something else,Taiwan,NaN
39438,39439,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America,NaN
40736,40737,50.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",South Africa,C#;Delphi;HTML/CSS;JavaScript;Perl;PHP;SQL;Vis...
40941,40942,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Germany,Bash/Shell (all shells);Elixir;Haskell;Ruby
41343,41344,50.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",United States of America,Bash/Shell (all shells);JavaScript;Lua;Scala;SQL
41695,41696,50.0,"Secondary school (e.g. American high school, G...",Armenia,NaN
46385,46386,50.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",United States of America,Bash/Shell (all shells);C;C++;Java;JavaScript;...
47198,47199,50.0,Some college/university study without earning ...,United States of America,Ada;Apex;Assembly;Bash/Shell (all shells);C;C#...
47274,47275,50.0,Some college/university study without earning ...,Denmark,C#;PowerShell;TypeScript
50590,50591,50.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",United States of America,HTML/CSS;Java;JavaScript
51147,51148,50.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Greece,HTML/CSS;Java;JavaScript;Python;Scala
52201,52202,50.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",France,C;JavaScript;Python;Zig
52510,52511,50.0,Some college/university study without earning ...,United States of America,C#;HTML/CSS;JavaScript;PowerShell;SQL
55828,55829,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America,C#;JavaScript;SQL;TypeScript
60331,60332,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Afghanistan,Ada
60387,60388,50.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",United States of America,Bash/Shell (all shells);C;C++;HTML/CSS;Java;Ja...

In [65]:
#you can also filter out multiple , let's say you want from specific countries
countries = ['United States of America', 'France', 'Germany']
filt = df_exp['Country'].isin(countries)

In [66]:
df_exp.loc[filt, 'Country']

1019     United States of America
1779     United States of America
2911     United States of America
6110     United States of America
6661     United States of America
12501                     Germany
17925    United States of America
19137    United States of America
19601    United States of America
20562    United States of America
20816    United States of America
25108    United States of America
26142    United States of America
28184    United States of America
29399    United States of America
30896    United States of America
33701    United States of America
37770                     Germany
39438    United States of America
40941                     Germany
41343    United States of America
46385    United States of America
47198    United States of America
50590    United States of America
52201                      France
52510    United States of America
55828    United States of America
60387    United States of America
Name: Country, dtype: object

In [67]:
#String method
filt = df_exp['LanguageWantToWorkWith'].str.contains('Python', na = False) #(na = false) is must to avoid error in NAN values
df_exp.loc[filt,['Country','LanguageWantToWorkWith']]

,Country,LanguageWantToWorkWith
2220,Argentina,C;C++;JavaScript;MicroPython;PowerShell;Python
2757,Taiwan,C;C++;Julia;Python
6661,United States of America,C;C#;HTML/CSS;Python;Swift
8256,Nigeria,Perl;PHP;PowerShell;Prolog;Python;R;Ruby;Rust;...
12501,Germany,C;C++;Python
17925,United States of America,Bash/Shell (all shells);C;Go;Python;SQL
19137,United States of America,C#;HTML/CSS;PHP;Python;R;SQL
19601,United States of America,Bash/Shell (all shells);JavaScript;Python;Rust...
20037,Niger,Ada;Apex;Assembly;Bash/Shell (all shells);C;C#...
20816,United States of America,Python;R;Ruby
21252,Israel,C;C#;Cobol;Java;Python;SQL
23683,Bangladesh,Ada;Apex;Assembly;Bash/Shell (all shells);C;C#...
26142,United States of America,C;C++;JavaScript;Python
29399,United States of America,C#;C++;Delphi;HTML/CSS;JavaScript;MATLAB;Power...
30896,United States of America,Python
32672,Canada,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...
34278,Nomadic,Ada;Apex;Assembly;Bash/Shell (all shells);C;C#...
38430,Netherlands,Assembly;C;C#;C++;Python
47198,United States of America,Ada;Apex;Assembly;Bash/Shell (all shells);C;C#...
51147,Greece,HTML/CSS;Java;JavaScript;Python;Scala
52201,France,C;JavaScript;Python;Zig
60387,United States of America,Bash/Shell (all shells);C;C++;HTML/CSS;Java;Ja...

## Modifying methods - Pandas_5

In [68]:
df_exp.rename(columns = {'WorkExp' : 'MonthExp'}, inplace = True)
df_exp

,ResponseId,MonthExp,EdLevel,Country,LanguageWantToWorkWith
819,820,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Denmark,C#;Prolog;TypeScript;VBA
1019,1020,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America,Bash/Shell (all shells);HTML/CSS;Java;JavaScri...
1779,1780,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America,Lisp;SQL
2220,2221,50.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Argentina,C;C++;JavaScript;MicroPython;PowerShell;Python
2757,2758,50.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Taiwan,C;C++;Julia;Python
2911,2912,50.0,Some college/university study without earning ...,United States of America,C#;C++;Delphi;SQL;Visual Basic (.Net)
6110,6111,50.0,Some college/university study without earning ...,United States of America,Bash/Shell (all shells);C#;HTML/CSS;JavaScript...
6661,6662,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America,C;C#;HTML/CSS;Python;Swift
8256,8257,50.0,"Secondary school (e.g. American high school, G...",Nigeria,Perl;PHP;PowerShell;Prolog;Python;R;Ruby;Rust;...
11548,11549,50.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Republic of North Macedonia,Delphi;Fortran;Perl;PHP
12501,12502,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Germany,C;C++;Python
12747,12748,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Bangladesh,JavaScript
17925,17926,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America,Bash/Shell (all shells);C;Go;Python;SQL
18954,18955,50.0,Some college/university study without earning ...,Canada,HTML/CSS;JavaScript
19137,19138,50.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",United States of America,C#;HTML/CSS;PHP;Python;R;SQL
19601,19602,50.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",United States of America,Bash/Shell (all shells);JavaScript;Python;Rust...
19712,19713,50.0,Some college/university study without earning ...,Philippines,NaN
20037,20038,50.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Niger,Ada;Apex;Assembly;Bash/Shell (all shells);C;C#...
20562,20563,50.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",United States of America,Clojure;Julia
20816,20817,50.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",United States of America,Python;R;Ruby
21252,21253,50.0,Some college/university study without earning ...,Israel,C;C#;Cobol;Java;Python;SQL
23384,23385,50.0,Primary/elementary school,Albania,Elixir;Lisp;Prolog
23683,23684,50.0,Something else,Bangladesh,Ada;Apex;Assembly;Bash/Shell (all shells);C;C#...
25108,25109,50.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",United States of America,Assembly;C;C++;Fortran
26142,26143,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America,C;C++;JavaScript;Python
27190,27191,50.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Nigeria,Ada
28184,28185,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America,Bash/Shell (all shells);C++;SQL
29399,29400,50.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",United States of America,C#;C++;Delphi;HTML/CSS;JavaScript;MATLAB;Power...
30896,30897,50.0,Some college/university study without earning ...,United States of America,Python
32672,32673,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Canada,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...
33101,33102,50.0,"Secondary school (e.g. American high school, G...",Afghanistan,Ada
33701,33702,50.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",United States of America,Apex;HTML/CSS;Java;JavaScript;SQL
34278,34279,50.0,Something else,Nomadic,Ada;Apex;Assembly;Bash/Shell (all shells);C;C#...
35090,35091,50.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Iceland,NaN
37770,37771,50.0,Some college/university study without earning ...,Germany,Java;JavaScript;Kotlin;Objective-C;Swift;TypeS...
38026,38027,50.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Thailand,NaN
38430,38431,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Netherlands,Assembly;C;C#;C++;Python
39055,39056,50.0,Something else,Taiwan,NaN
39438,39439,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America,NaN
40736,40737,50.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",South Africa,C#;Delphi;HTML/CSS;JavaScript;Perl;PHP;SQL;Vis...
40941,40942,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Germany,Bash/Shell (all shells);Elixir;Haskell;Ruby
41343,41344,50.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",United States of America,Bash/Shell (all shells);JavaScript;Lua;Scala;SQL
41695,41696,50.0,"Secondary school (e.g. American high school, G...",Armenia,NaN
46385,46386,50.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",United States of America,Bash/Shell (all shells);C;C++;Java;JavaScript;...
47198,47199,50.0,Some college/university study without earning ...,United States of America,Ada;Apex;Assembly;Bash/Shell (all shells);C;C#...
47274,47275,50.0,Some college/university study without earning ...,Denmark,C#;PowerShell;TypeScript
50590,50591,50.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",United States of America,HTML/CSS;Java;JavaScript
51147,51148,50.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Greece,HTML/CSS;Java;JavaScript;Python;Scala
52201,52202,50.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",France,C;JavaScript;Python;Zig
52510,52511,50.0,Some college/university study without earning ...,United States of America,C#;HTML/CSS;JavaScript;PowerShell;SQL
55828,55829,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America,C#;JavaScript;SQL;TypeScript
60331,60332,50.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Afghanistan,Ada
60387,60388,50.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",United States of America,Bash/Shell (all shells);C;C++;HTML/CSS;Java;Ja...

In [69]:
df_exp['MonthExp'] = df_exp['MonthExp'].apply(lambda x: x*12)
df_exp

,ResponseId,MonthExp,EdLevel,Country,LanguageWantToWorkWith
819,820,600.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Denmark,C#;Prolog;TypeScript;VBA
1019,1020,600.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America,Bash/Shell (all shells);HTML/CSS;Java;JavaScri...
1779,1780,600.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America,Lisp;SQL
2220,2221,600.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Argentina,C;C++;JavaScript;MicroPython;PowerShell;Python
2757,2758,600.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Taiwan,C;C++;Julia;Python
2911,2912,600.0,Some college/university study without earning ...,United States of America,C#;C++;Delphi;SQL;Visual Basic (.Net)
6110,6111,600.0,Some college/university study without earning ...,United States of America,Bash/Shell (all shells);C#;HTML/CSS;JavaScript...
6661,6662,600.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America,C;C#;HTML/CSS;Python;Swift
8256,8257,600.0,"Secondary school (e.g. American high school, G...",Nigeria,Perl;PHP;PowerShell;Prolog;Python;R;Ruby;Rust;...
11548,11549,600.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Republic of North Macedonia,Delphi;Fortran;Perl;PHP
12501,12502,600.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Germany,C;C++;Python
12747,12748,600.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Bangladesh,JavaScript
17925,17926,600.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America,Bash/Shell (all shells);C;Go;Python;SQL
18954,18955,600.0,Some college/university study without earning ...,Canada,HTML/CSS;JavaScript
19137,19138,600.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",United States of America,C#;HTML/CSS;PHP;Python;R;SQL
19601,19602,600.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",United States of America,Bash/Shell (all shells);JavaScript;Python;Rust...
19712,19713,600.0,Some college/university study without earning ...,Philippines,NaN
20037,20038,600.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Niger,Ada;Apex;Assembly;Bash/Shell (all shells);C;C#...
20562,20563,600.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",United States of America,Clojure;Julia
20816,20817,600.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",United States of America,Python;R;Ruby
21252,21253,600.0,Some college/university study without earning ...,Israel,C;C#;Cobol;Java;Python;SQL
23384,23385,600.0,Primary/elementary school,Albania,Elixir;Lisp;Prolog
23683,23684,600.0,Something else,Bangladesh,Ada;Apex;Assembly;Bash/Shell (all shells);C;C#...
25108,25109,600.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",United States of America,Assembly;C;C++;Fortran
26142,26143,600.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America,C;C++;JavaScript;Python
27190,27191,600.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Nigeria,Ada
28184,28185,600.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America,Bash/Shell (all shells);C++;SQL
29399,29400,600.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",United States of America,C#;C++;Delphi;HTML/CSS;JavaScript;MATLAB;Power...
30896,30897,600.0,Some college/university study without earning ...,United States of America,Python
32672,32673,600.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Canada,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...
33101,33102,600.0,"Secondary school (e.g. American high school, G...",Afghanistan,Ada
33701,33702,600.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",United States of America,Apex;HTML/CSS;Java;JavaScript;SQL
34278,34279,600.0,Something else,Nomadic,Ada;Apex;Assembly;Bash/Shell (all shells);C;C#...
35090,35091,600.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Iceland,NaN
37770,37771,600.0,Some college/university study without earning ...,Germany,Java;JavaScript;Kotlin;Objective-C;Swift;TypeS...
38026,38027,600.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Thailand,NaN
38430,38431,600.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Netherlands,Assembly;C;C#;C++;Python
39055,39056,600.0,Something else,Taiwan,NaN
39438,39439,600.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America,NaN
40736,40737,600.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",South Africa,C#;Delphi;HTML/CSS;JavaScript;Perl;PHP;SQL;Vis...
40941,40942,600.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Germany,Bash/Shell (all shells);Elixir;Haskell;Ruby
41343,41344,600.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",United States of America,Bash/Shell (all shells);JavaScript;Lua;Scala;SQL
41695,41696,600.0,"Secondary school (e.g. American high school, G...",Armenia,NaN
46385,46386,600.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",United States of America,Bash/Shell (all shells);C;C++;Java;JavaScript;...
47198,47199,600.0,Some college/university study without earning ...,United States of America,Ada;Apex;Assembly;Bash/Shell (all shells);C;C#...
47274,47275,600.0,Some college/university study without earning ...,Denmark,C#;PowerShell;TypeScript
50590,50591,600.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",United States of America,HTML/CSS;Java;JavaScript
51147,51148,600.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Greece,HTML/CSS;Java;JavaScript;Python;Scala
52201,52202,600.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",France,C;JavaScript;Python;Zig
52510,52511,600.0,Some college/university study without earning ...,United States of America,C#;HTML/CSS;JavaScript;PowerShell;SQL
55828,55829,600.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America,C#;JavaScript;SQL;TypeScript
60331,60332,600.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Afghanistan,Ada
60387,60388,600.0,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",United States of America,Bash/Shell (all shells);C;C++;HTML/CSS;Java;Ja...